Add CARGO_NET_GIT_FETCH_WITH_CLI=true
to avoid:

```
$ cargo build
    Updating crates.io index
error: failed to get `anyhow` as a dependency of package [...]

Caused by:
  failed to fetch `https://github.com/rust-lang/crates.io-index`

Caused by:
  failed to authenticate when downloading repository: git@github.com:rust-lang/crates.io-index

  * attempted ssh-agent authentication, but no usernames succeeded: `git`

  if the git CLI succeeds then `net.git-fetch-with-cli` may help here
  https://doc.rust-lang.org/cargo/reference/config.html#netgit-fetch-with-cli
Caused by:
  no authentication available
```

when .gitconfig contains:

```
[url "git@github.com:"]
        insteadOf = https://github.com/
```